apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager
  namespace: argocd
spec:
  destination:
    namespace: taskmanager
    server: https://kubernetes.default.svc

  project: default

  source:
    repoURL: https://github.com/saros-dev/devops-task-manager
    targetRevision: main
    path: k8s/helm/taskmanager

    helm:
      parameters:
        - name: image.tag
          value: "latest"   # فعلاً placeholder (بعداً حذف می‌کنیم)

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
