image:
  repository: sarosdev/taskmanager-backend
  tag: "cfd4d910eb27baa627eefd1cc3091e60b7f8f94f"
replicaCount: 2

service:
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
