image:
  repository: sarosdev/taskmanager-backend
  tag: "e382a44dea4ab69ec16fb4d6437ac6cbcea4bef1"
replicaCount: 2

service:
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
