image:
  repository: sarosdev/taskmanager-backend
  digest: sha256:4b5900ed6971d1c79844e14d698c5898a8e61d7cf5b97d743bf78dd78abaeba3
replicaCount: 2

service:
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
