name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Application
        run: mvn -f backend/taskmanager/pom.xml clean package -DskipTests

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:latest \
            backend/taskmanager

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend \
            backend=${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:${{ github.sha }} \
            -n taskmanager

          kubectl rollout status deployment/backend -n taskmanager

