name: CD Pipeline (GitOps Safe)

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  update-manifest:
    if: >
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Variables
        run: |
          echo "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update Helm Tag
        run: |
          sed -i "s|tag: .*|tag: \"${IMAGE_TAG}\"|g" k8s/helm/taskmanager/values.yaml

      - name: Check For Changes
        run: |
          git diff --quiet && echo "NO_CHANGES=true" >> $GITHUB_ENV || echo "NO_CHANGES=false" >> $GITHUB_ENV

      - name: Create Branch
        if: env.NO_CHANGES == 'false'
        run: |
          BRANCH="ci/update-image-${IMAGE_TAG}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b $BRANCH

      - name: Commit Changes
        if: env.NO_CHANGES == 'false'
        run: |
          git add k8s/helm/taskmanager/values.yaml
          git commit -m "chore: update image tag ${IMAGE_TAG}"

      - name: Push Branch
        if: env.NO_CHANGES == 'false'
        run: |
          git push origin $BRANCH

      - name: Create Pull Request
        if: env.NO_CHANGES == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore: deploy image ${IMAGE_TAG}" \
            --body "Automated GitOps deployment PR" \
            --base main \
            --head $BRANCH
