name: CI Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "k8s/helm/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -f backend/taskmanager/pom.xml clean package -DskipTests

      # 🐳 Docker Login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🐳 Build + Push Image
      - name: Build & Push Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/taskmanager-backend:${{ github.sha }}

          docker build -t $IMAGE backend/taskmanager
          docker push $IMAGE
